// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBr6hGsivPJPRsOXQTr5QgR9lx4QvvAbg',
    appId: '1:562785229941:web:ce669c7aa745d3aa51ac3c',
    messagingSenderId: '562785229941',
    projectId: 'resq-a42ed',
    authDomain: 'resq-a42ed.firebaseapp.com',
    storageBucket: 'resq-a42ed.appspot.com',
    measurementId: 'G-TTD5BPHTZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIKJQVO-rUfND13e-9PO_a-n1WWQWw_BU',
    appId: '1:562785229941:android:854dd31456211cc151ac3c',
    messagingSenderId: '562785229941',
    projectId: 'resq-a42ed',
    storageBucket: 'resq-a42ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNyzkIsWlQ7EgdKYRLVN2joVxIY42Jc4U',
    appId: '1:562785229941:ios:76fffc473d0a62ac51ac3c',
    messagingSenderId: '562785229941',
    projectId: 'resq-a42ed',
    storageBucket: 'resq-a42ed.appspot.com',
    iosBundleId: 'com.example.resq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNyzkIsWlQ7EgdKYRLVN2joVxIY42Jc4U',
    appId: '1:562785229941:ios:7ae3608e00c143a251ac3c',
    messagingSenderId: '562785229941',
    projectId: 'resq-a42ed',
    storageBucket: 'resq-a42ed.appspot.com',
    iosBundleId: 'com.example.resq.RunnerTests',
  );
}
